---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

env:
  DESTDIR: /tmp/build
  LUA_LIB_DIR: /usr/local/openresty/lualib
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
      release-git-tag: ${{ steps.release.outputs.release-git-tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2.2.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  artifacts:
    needs: release
    name: Create Release Artifacts
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
      - name: Rsync atc-router files
        run: |
          rsync -av --ignore-existing atc-router/ .
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: '-C target-feature=-crt-static' # Required for aarch64-unknown-linux-musl
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Install, Compress, and rename artifacts
        env:
          DESTDIR: ${{ env.DESTDIR }}
        run: |
          make install
          tar -C /tmp/build/ -czvf ${{ matrix.target }}.tar.gz .
      - name: Add Release Artifacts to the Github Release
        if: ${{ needs.release.outputs.published == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release.outputs.release-git-tag }}
          files: ${{ matrix.target }}.tar.gz

  cleanup:
    needs: [release]
    if: failure()
    name: Cleanup Half-Created Release/Tag
    runs-on: ubuntu-latest
    steps:
    - name: Delete GitHub Release
      run: |
        if gh release view ${{ needs.release.outputs.release-git-tag }} >/dev/null 2>&1; then
          gh release delete ${{ needs.release.outputs.release-git-tag }} --yes
        fi
    - name: Delete GitHub Tag
      run: |
        if git show-ref --tags ${{ needs.release.outputs.release-git-tag }}; then
          git tag -d ${{ needs.release.outputs.release-git-tag }}
          git push origin :refs/tags/${{ needs.release.outputs.release-git-tag }}
        fi
